const mongoose=require('mongoose')

const courseSchema=mongoose.Schema({
    courseID:String,
    name:String,
    type:String,
    coordinator:{
        type:mongoose.Schema.ObjectId,
        default:"",
        ref:"prof"
    },
    program:String,
    sem:String,
    year:Number,
    oddEven:String,
    coStatements:[
        {
            description:String,
            bloomsLevel:String
        }
    ],
    coAttainment:[
        {
            targetSet:Number,
            direct:{
                inSem:Number,
                endSem:Number,
                finalCo:Number
            },
            overall:{
                inSem:Number,
                endSem:Number,
                finalCo:Number
            }
        }
    ],
    coPoMapping:[
        {
            coNum:Number,
            poNum:Number,
            value:Number,
        }
    ],
    coPsoMapping:[
        {
            coNum:Number,
            psoNum:Number,
            value:Number
        }
    ],
    dept:{
        type:mongoose.Schema.ObjectId,
        ref:"dept"
    },
    ass1:[
        {
            qNo:Number,
            part:String,
            co:Number,
            maxMarks:Number
        }
    ],
    ass2:[
        {
            qNo:Number,
            part:String,
            co:Number,
            maxMarks:Number
        }
    ],
    ass3:[
        {
            qNo:Number,
            part:String,
            co:Number,
            maxMarks:Number
        }
    ],
    ass4:[
        {
            qNo:Number,
            part:String,
            co:Number,
            maxMarks:Number
        }
    ],
    midSem:[
        {
            qNo:Number,
            part:String,
            co:Number,
            maxMarks:Number
        }
    ],
    endSem:[
        {
            qNo:Number,
            part:String,
            co:Number,
            maxMarks:Number
        }
    ]
})

module.exports=mongoose.model("course",courseSchema)